// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "AbilitySystemComponent.h"
#include "AttributeSet.h"
#include "TDWAttributeSet.generated.h"

#define ATTRIBUTE_ACCESSORS(ClassName, PropertyName) \
GAMEPLAYATTRIBUTE_PROPERTY_GETTER(ClassName, PropertyName) \
GAMEPLAYATTRIBUTE_VALUE_GETTER(PropertyName) \
GAMEPLAYATTRIBUTE_VALUE_SETTER(PropertyName) \
GAMEPLAYATTRIBUTE_VALUE_INITTER(PropertyName)

class ATDWCharacter;
class UCharacterMovementComponent;

/**
 * 
 */
UCLASS()
class THEDARKWEST_API UTDWAttributeSet : public UAttributeSet
{
	GENERATED_BODY()
	
public:
	virtual void PreAttributeChange(const FGameplayAttribute& Attribute, float& NewValue) override;
	virtual void PostGameplayEffectExecute(const struct FGameplayEffectModCallbackData& Data) override;
	virtual void PostAttributeChange(const FGameplayAttribute& Attribute, float OldValue, float NewValue) override;
	
	UCharacterMovementComponent* GetCharacterMovementComponent() const;
	ATDWCharacter* GetTDWCharacter() const;
	
	/*
	 * Vital Attributes ----------------------------------------------
	 */
	
	/** Health attribute, when it reaches zero the character dies */
	UPROPERTY(BlueprintReadOnly, Category = "Vital Attributes")
	FGameplayAttributeData Health;
	ATTRIBUTE_ACCESSORS(UTDWAttributeSet, Health);

	/** Maximum Health attribute 
	 * This is the attribute that gets modified when applying health buffs or debuffs
	 */
	UPROPERTY(BlueprintReadOnly, Category = "Vital Attributes")
	FGameplayAttributeData MaxHealth;
	ATTRIBUTE_ACCESSORS(UTDWAttributeSet, MaxHealth);
	
	/*
	 * Movement Attributes ----------------------------------------------
	 */
	
	/** Movement Speed. 
	 * The value is multiplied by 10 to get the actual character movement speed
	 * 
	 * Changes to this attribute will automatically update the CharacterMovementComponent's MaxWalkSpeed
	 * 
	 * This attribute could stay on another AttributeSet related to movement or non-vital attributes
	 */
	UPROPERTY(BlueprintReadOnly, Category = "Movement Attributes")
	FGameplayAttributeData MoveSpeed;
	ATTRIBUTE_ACCESSORS(UTDWAttributeSet, MoveSpeed);
	
	/*
	 * Damage Attributes ----------------------------------------------
	 */
	
	/** Damage Amount attribute, used to apply damage to targets 
	 * In a scalable system, this final value is generated by the weapon, ammo, character attributes, buffs, debuffs, etc.
	 * For now, we will simplify it to a single attribute that will be set by the character start attribute values.
	 */
	UPROPERTY(BlueprintReadOnly, Category = "Damage Attributes")
	FGameplayAttributeData DamageAmount;
	ATTRIBUTE_ACCESSORS(UTDWAttributeSet, DamageAmount);
};
